apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-track-catalogo
spec:
  template:
    spec:
      containers:
        - name: service-track-catalogo
          imagePullPolicy: IfNotPresent
