apiVersion: 1

contactPoints:
  - orgId: 1
    name: plantao-local
    receivers:
      - uid: plantao-webhook
        type: webhook
        settings:
          url: http://alertas:8080/plantao
          httpMethod: POST
        disableResolveMessage: false

policies:
  - orgId: 1
    receiver: plantao-local
    group_by:
      - grafana_folder
      - alertname
    group_wait: 10s
    group_interval: 30s
    repeat_interval: 1h
    routes:
      - receiver: plantao-local
        object_matchers:
          - ["severidade", "=", "critica"]
        group_wait: 0s
        repeat_interval: 15m
